# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('update', '__first__'),
        ('sparql', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('slug', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('query', models.TextField()),
                ('mapping', models.TextField(blank=True)),
                ('update_mapping', models.BooleanField()),
                ('groups', models.CharField(blank=True, max_length=256)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('queued', 'Queued'), ('active', 'Active')], default='idle', max_length=10)),
                ('last_queued', models.DateTimeField(blank=True, null=True)),
                ('last_started', models.DateTimeField(blank=True, null=True)),
                ('last_completed', models.DateTimeField(blank=True, null=True)),
                ('item_count', models.IntegerField(blank=True, null=True)),
                ('stores', models.ManyToManyField(blank=True, to='sparql.Store')),
                ('update_after', models.ManyToManyField(blank=True, to='update.UpdateDefinition')),
            ],
            options={
                'verbose_name_plural': 'indexes',
            },
        ),
    ]
