# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 11:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sparql', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomatedAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('domain', 'Source domain'), ('ip', 'Submitting IP'), ('hostname', 'Submitting hostname')], max_length=8)),
                ('value', models.CharField(max_length=128)),
                ('action', models.CharField(choices=[('accepted', 'Accept'), ('rejected', 'Reject')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='InboundPingback',
            fields=[
                ('slug', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('source', models.URLField()),
                ('target', models.URLField()),
                ('user_agent', models.TextField(blank=True)),
                ('remote_addr', models.GenericIPAddressField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('data', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('new', 'New'), ('queued', 'Queued'), ('invalid', 'Invalid pingback'), ('processing', 'Being processed'), ('pending', 'Pending moderation'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('published', 'Published to store')], default='new', max_length=10)),
                ('invalid_reason', models.TextField(blank=True, choices=[('unexpected-media-type', 'Unexpected media type'), ('non-targetable-host', 'Pingbacks not accepted for the given target'), ('unsupported-source-scheme', 'Source URL had an unsupported scheme'), ('no-link-found', "Couldn't find a link from the source to the target"), ('invalid-html', 'Could not parse remote document as HTML'), ('http-error', 'Could not download remote document')])),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sparql.Store')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
