# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 12:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('query_endpoint', models.URLField()),
                ('update_endpoint', models.URLField(blank=True, null=True)),
                ('graph_store_endpoint', models.URLField(blank=True, null=True)),
            ],
            options={
                'permissions': (('administer_store', 'can administer'), ('query_store', 'can query'), ('update_store', 'can update')),
            },
        ),
        migrations.CreateModel(
            name='UserPrivileges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_concurrent_queries', models.BooleanField()),
                ('disable_throttle', models.BooleanField()),
                ('throttle_threshold', models.FloatField(blank=True, null=True)),
                ('deny_threshold', models.FloatField(blank=True, null=True)),
                ('intensity_decay', models.FloatField(blank=True, null=True)),
                ('disable_timeout', models.BooleanField()),
                ('maximum_timeout', models.IntegerField(null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
