# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updatelogrecord',
            name='update_log',
        ),
        migrations.AddField(
            model_name='updatelog',
            name='log',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UpdateLogRecord',
        ),
    ]
